# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aNu35WPEyLta0yzykQwJlm7QafFNAl48
"""

# -*- coding: utf-8 -*-
"""Plant_Leaves_PyTorch

Automatically generated by Colab / Adapted for Local GPU.
"""

import os
import copy
import torch
import torch.nn as nn
import torch.optim as optim
import torchvision.transforms as transforms
import torchvision.datasets as datasets
import torchvision.models as models
from torch.utils.data import DataLoader, random_split
import matplotlib.pyplot as plt
import numpy as np
import kagglehub
from tqdm import tqdm
# Download latest version
path = kagglehub.dataset_download("abdallahalidev/plantvillage-dataset")
print("Path to dataset files:", path)

"""**CORECT DIR**
---
only using colored images so that the model is more robust
"""
dataset_path = os.path.join(path, 'plantvillage dataset', 'color')
print("Classes found:", len(os.listdir(dataset_path)))

"""First Time using PyTorch
---
1. Loading the dataset
2. assigns labels
3. scalling the images (ToTensor handles the 1/255 math automatically!)
4. creating batches
5. splits train/validation
"""

# PyTorch Augmentation happens HERE, before the model.
# more robust dataset by adding some noise
train_transforms = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.RandomHorizontalFlip(),
    transforms.RandomRotation(5), # 0.05 rad is roughly 3-5 degrees
    transforms.ToTensor(), # **normalization** as a instance of transforms class that has __call__()
])

# Validation shouldn't be rotated or flipped!
val_transforms = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
])

# Load the entire dataset
full_dataset = datasets.ImageFolder(root=dataset_path, transform=train_transforms)
class_names = full_dataset.classes
num_classes = len(class_names)

# Split 80/20
train_size = int(0.8 * len(full_dataset))
val_size = len(full_dataset) - train_size
train_dataset, val_dataset = random_split(full_dataset, [train_size, val_size])

# Override the validation dataset transform so it doesn't get random flips
val_dataset.dataset.transform = val_transforms

"""hence i can use DataLoader for recalling each batch form my boht train and validation dataset"""
# This replaces AUTOTUNE and .prefetch(). num_workers=2 is safe for a laptop.
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True, num_workers=2)
val_loader = DataLoader(val_dataset, batch_size=32, shuffle=False, num_workers=2)

"""Checking the batch if its diverse by plotting the images"""
# Grab one batch of 32 images
dataiter = iter(train_loader)
images, labels = next(dataiter)

plt.figure(figsize=(10,10))
for i in range(9):
    ax = plt.subplot(3,3,i+1)
    # PyTorch images are (Color, Height, Width). Matplotlib needs (Height, Width, Color).
    img = np.transpose(images[i].numpy(), (1, 2, 0))
    plt.imshow(img)
    plt.title(class_names[labels[i]])
    plt.axis("off")
plt.show()

print("\n--- Setup Complete. Starting Model Building ---")

# Setup GPU if available (This will use his 8GB VRAM!)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Training on device: {device}")

def build_model(model_name, num_classes):
    """Downloads the brain, freezes it, and swaps the final layer."""
    if model_name == 'mobilenet':
        model = models.mobilenet_v2(weights=models.MobileNet_V2_Weights.IMAGENET1K_V1)
        # Freeze base
        for param in model.parameters(): param.requires_grad = False
        # Swap head
        model.classifier[1] = nn.Linear(model.classifier[1].in_features, num_classes)

    elif model_name == 'resnet':
        model = models.resnet50(weights=models.ResNet50_Weights.IMAGENET1K_V1)
        for param in model.parameters(): param.requires_grad = False
        model.fc = nn.Linear(model.fc.in_features, num_classes)

    elif model_name == 'efficientnet':
        model = models.efficientnet_b0(weights=models.EfficientNet_B0_Weights.IMAGENET1K_V1)
        for param in model.parameters(): param.requires_grad = False
        model.classifier[1] = nn.Linear(model.classifier[1].in_features, num_classes)

    return model.to(device)

# --- PYTORCH EARLY STOPPING (Custom built since PyTorch doesn't have it built-in) ---
class EarlyStopping:
    def __init__(self, patience=3):
        self.patience = patience
        self.counter = 0
        self.best_acc = 0.0
        self.early_stop = False
        self.best_weights = None

    def __call__(self, val_acc, model):
        if val_acc > self.best_acc:
            self.best_acc = val_acc
            self.best_weights = copy.deepcopy(model.state_dict())
            self.counter = 0
        else:
            self.counter += 1
            if self.counter >= self.patience:
                self.early_stop = True

# --- THE PYTORCH TRAINING LOOP (Replaces model.fit) ---
# --- THE UPGRADED PYTORCH TRAINING LOOP (With Keras-style Progress Bar) ---
def train_model(model, train_loader, val_loader, epochs=50):
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=0.001)
    early_stopper = EarlyStopping(patience=3)

    for epoch in range(epochs):
        model.train()
        running_loss, correct, total = 0.0, 0, 0

        # 1. WRAP THE TRAIN LOADER IN TQDM
        progress_bar = tqdm(train_loader, desc=f'Epoch {epoch+1}/{epochs}', unit='batch')

        for inputs, labels in progress_bar:
            inputs, labels = inputs.to(device), labels.to(device)

            optimizer.zero_grad()
            outputs = model(inputs)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()

            # Math for the progress bar
            running_loss += loss.item()
            _, predicted = torch.max(outputs.data, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()

            # 2. UPDATE THE PROGRESS BAR IN REAL-TIME
            current_loss = running_loss / (total / inputs.size(0))
            current_acc = correct / total
            progress_bar.set_postfix(loss=f'{current_loss:.4f}', acc=f'{current_acc:.4f}')

        train_acc = correct / total

        # Validation Phase
        model.eval()
        val_correct, val_total = 0, 0

        print("Running Validation...") # Small print so you know it's testing
        with torch.no_grad():
            for inputs, labels in val_loader:
                inputs, labels = inputs.to(device), labels.to(device)
                outputs = model(inputs)
                _, predicted = torch.max(outputs.data, 1)
                val_total += labels.size(0)
                val_correct += (predicted == labels).sum().item()

        val_acc = val_correct / val_total

        # Final print for the epoch summary
        print(f"Epoch {epoch+1} Summary -> Train Acc: {train_acc:.4f} | Val Acc: {val_acc:.4f}")

        # Check Early Stopping
        early_stopper(val_acc, model)
        if early_stopper.early_stop:
            print("\n🚨 Early stopping triggered! Restoring best weights...")
            model.load_state_dict(early_stopper.best_weights)
            break

    return model

# ---------------------------------------------------------
# EXECUTE TRAINING AND SAVE
# ---------------------------------------------------------
models_to_train = ['mobilenet', 'resnet', 'efficientnet']

for name in models_to_train:
    print(f"\n========== Training {name.upper()} ==========")
    model = build_model(name, num_classes)
    trained_model = train_model(model, train_loader, val_loader, epochs=50)

    # Save the brain! (.pth is the PyTorch standard)
    save_path = f"{name}_plants.pth"
    torch.save(trained_model.state_dict(), save_path)
    print(f"Saved {name} to {save_path}")

print("\nAll models trained and saved successfully!")